<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Title>VIRPIL USB Device Cleaner</Title>
    <Description>Supprime complètement les périphériques VIRPIL du système et du registre Windows</Description>
    <Version>1.0.0</Version>
    <StartupObject>VirpilCleanup.App</StartupObject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>


</Project>
